version: '3'
services:
  vuekot-api-server:
    build:
      context: api-server/
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
    volumes:
      - ./api-server:/app
      - /app/.gradle
      - gradle-cache:/root/.gradle/caches/modules-2/files-2.1/
    restart: always
    depends_on:
      - postgres-db
    networks:
      - vuekot
      - database  
  # vuekot-front:
  #   build:
  #     context: front/
  #   command: bash -c "yarn install && yarn run dev"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./front:/app
  postgres-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - vuekot
      - database  
networks:
  vuekot:
  database:      
volumes:
  gradle-cache:  